version: "3.8"

services:
  quartz:
    image: ghcr.io/snoilt/quartzalgo:latest  # zieht neuen Digest automatisch
    container_name: quartz-site
    ports:
      - "9441:8080"
    restart: unless-stopped